// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm_jgCiw0tasDk2wguwysXvQN6rRMg35s',
    appId: '1:1028407657744:web:27b4a7f2828c507a43d195',
    messagingSenderId: '1028407657744',
    projectId: 'mobile-computing-a66bb',
    authDomain: 'mobile-computing-a66bb.firebaseapp.com',
    storageBucket: 'mobile-computing-a66bb.appspot.com',
    measurementId: 'G-HZ9JWXB2M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_x70bUb3k0Wk7X8wN-N44sYchZ9EXfM',
    appId: '1:1028407657744:android:b3dfcfa5d24c351c43d195',
    messagingSenderId: '1028407657744',
    projectId: 'mobile-computing-a66bb',
    storageBucket: 'mobile-computing-a66bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI9qPcAoR48npmdMuXKcxKsAznRplVM5A',
    appId: '1:1028407657744:ios:49814be24eabf3fb43d195',
    messagingSenderId: '1028407657744',
    projectId: 'mobile-computing-a66bb',
    storageBucket: 'mobile-computing-a66bb.appspot.com',
    iosBundleId: 'com.example.mobileComputing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI9qPcAoR48npmdMuXKcxKsAznRplVM5A',
    appId: '1:1028407657744:ios:75a8576af5140d1d43d195',
    messagingSenderId: '1028407657744',
    projectId: 'mobile-computing-a66bb',
    storageBucket: 'mobile-computing-a66bb.appspot.com',
    iosBundleId: 'com.example.mobileComputing.RunnerTests',
  );
}
